Git ignore test alex
Larisa-Antsifrova/project-filmoteka pull request #80
Opened 2021-01-20 20:57 UTC by AlexBelozertsev

отработана загрузка и логика трейлера (необходим рефакторинг)
обнаружен баг отображения страниц при поиске

2021-01-20 21:45 UTC, Larisa-Antsifrova requested changes
Леша, есть только маленькие моменты :) А в общем, ты молодец !

2021-01-20 21:45 UTC, Larisa-Antsifrova commented on src/js/2searchAndPaginationHomePage.js
> +function renderPageOnNumBtn(evt) {
Нужна ли эта функция? :)

2021-01-20 21:45 UTC, Larisa-Antsifrova commented on src/js/2searchAndPaginationHomePage.js
> +      if (!results.length) {
Супер!

2021-01-20 21:45 UTC, Larisa-Antsifrova commented on src/js/2searchAndPaginationHomePage.js
> +  const YouTubeURL = 'https://www.youtube.com//embed/';
Константы называются - все большие буквы. Сейчас это похоже на имя класса. Лучше, YOUTUBE_URL.

2021-01-20 21:45 UTC, Larisa-Antsifrova commented on src/js/2searchAndPaginationHomePage.js
> +trailerSection.addEventListener('click', openModale);
openModale - Modal без "е" в конце :))

2021-01-20 21:45 UTC, Larisa-Antsifrova commented on src/js/2searchAndPaginationHomePage.js
> +};
О! Лёша, ты молодец, что думаешь о снятии слушателей :))

2021-01-21 10:00 UTC, AlexBelozertsev commented on src/js/2searchAndPaginationHomePage.js
> +function renderPageOnNumBtn(evt) {
Это при прошлом купировании моего кода ты его оставила. если для пагинации он не нужен - сноси

2021-01-21 10:01 UTC, AlexBelozertsev commented on src/js/2searchAndPaginationHomePage.js
> +  const YouTubeURL = 'https://www.youtube.com//embed/';
ок, исправлю

2021-01-21 10:01 UTC, AlexBelozertsev commented on src/js/2searchAndPaginationHomePage.js
> +trailerSection.addEventListener('click', openModale);
сори, опечатка

2021-01-21 10:04 UTC, AlexBelozertsev commented on src/js/2searchAndPaginationHomePage.js
> +};
да, это я еще помню)

2021-01-21 10:19 UTC, Larisa-Antsifrova commented on src/js/2searchAndPaginationHomePage.js
> +};
openModale - только тут появляется, а везде openModal.

2021-01-21 11:17 UTC, Larisa-Antsifrova approved these changes

2021-01-21 11:18 UTC, merged